name: Update CNBC Dataset

on:
  workflow_dispatch:   # avvio manuale
  schedule:
    - cron: "0 8 * * *"   # ogni giorno alle 08:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl datasets huggingface_hub newspaper3k transformers torch accelerate lxml lxml_html_clean

      # Setup ChromeDriver (usando GitHub Action)
      - name: Setup ChromeDriver
        uses: browser-actions/setup-chromedriver@v1
        with:
          chromedriver-version: latest

      # Clean temporary files before run
      - name: Clean temporary files before run
        run: rm -rf /tmp/*

      # Run scraper & NLP script
      - name: Run scraper
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Scraper.py

      # Clean temporary files after run
      - name: Clean temporary files after run
        run: rm -rf /tmp/*
